mod.id=sounds
mod.name=Sounds
mod.description=A highly configurable sound overhaul mod that adds new sound effects while improving vanilla sounds too.
mod.license=ARR
mod.version=2.6.0
mod.group=dev.imb11.sounds
mod.required=mru
publish.modrinth=ZouiUX7t
publish.curseforge=925889
publish.dependencies.fabric=fabric-api,yacl,mru
publish.dependencies.neoforge=yacl,mru
