modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/IMB11/Fog/issues"
license="All-Rights-Reserved"

[[mods]]
modId="fog"
version="${version}"
displayName="Fog"
displayURL="https://imb11.dev/"
logoFile="assets/fog/icon.png"
authors="IMB11,Steveplays"
description="An expansive and dynamic overhaul to Minecraft's fog rendering system."

[[mixins]]
config="fog.mixins.json"

[mc-publish]
dependencies=["architectury-api", "yacl"]

[[dependencies.fog]]
modId="neoforge"
type="required"
versionRange="${target_loader}"
ordering="NONE"
side="CLIENT"

[[dependencies.fog]]
modId="minecraft"
type="required"
versionRange="${target_minecraft}"
ordering="NONE"
side="CLIENT"

[[dependencies.fog]]
modId="mru"
type="required"
versionRange="[${target_mru},)"
ordering="NONE"
side="CLIENT"

[[dependencies.fog]]
modId="architectury"
type="required"
versionRange="[${target_architectury},)"
ordering="AFTER"
side="CLIENT"

[[dependencies.fog]]
modId="yet_another_config_lib_v3"
type="required"
versionRange="[${target_yacl},)"
ordering="NONE"
side="CLIENT"
