[versions]
jsonlang = "2.1-beta.4"
jspecify = "1.0.0"
kaleido = "0.3.3+1.3.2"
loom = "1.18.2"
mod-publish = "2.2.1"
moddev = "2.0.147"

[libraries]
jsonlang-plugin = { module = "dev.kikugie.postprocess.jsonlang:dev.kikugie.postprocess.jsonlang.gradle.plugin", version.ref = "jsonlang" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
kaleido = { module = "folk.sisby:kaleido-config", version.ref = "kaleido" }
loom-plugin = { module = "net.fabricmc:fabric-loom", version.ref = "loom" }
mod-publish-plugin = { module = "me.modmuss50.mod-publish-plugin:me.modmuss50.mod-publish-plugin.gradle.plugin", version.ref = "mod-publish" }
moddev-plugin = { module = "net.neoforged.moddev:net.neoforged.moddev.gradle.plugin", version.ref = "moddev" }
