mod.id=glass
mod.name=GLASS Remastered
mod.description=General Laymans' Aesthetic Spying Screen, remastered for modern Minecraft.
mod.license=All-Rights-Reserved
mod.version=1.0.0-beta
mod.group=dev.imb11.glass
mod.datagen=true
publish.modrinth=5TABPEIf
publish.curseforge=1090535
publish.dependencies.fabric=fabric-api
