mod.id=shields
mod.name=Shields
mod.description=A vanilla+ expansion to shields. Adds various new shields inline with the vanilla armor system and shield plating upgrades. Includes new and improved enchantment support.
mod.license=ARR
mod.version=1.4.2
mod.group=dev.imb11.shields
mod.required=mru
publish.modrinth=GPVR65Ju
publish.curseforge=1169734
publish.dependencies.fabric=fabric-api,yacl,mru
publish.dependencies.neoforge=yacl,mru
