mod.id=fog
mod.name=Fog
mod.description=An expansive and dynamic overhaul to Minecraft's fog rendering system.
mod.license=All-Rights-Reserved
mod.version=1.12.0
mod.group=dev.imb11.fog
mod.required=mru
mod.environment=client
publish.modrinth=WuGVWUF2
publish.curseforge=815438
publish.dependencies.fabric=fabric-api,architectury-api,yacl,mru
publish.dependencies.neoforge=architectury-api,yacl,mru
