modLoader="javafml"
loaderVersion="[4,)"
license="All-Rights-Reserved"

[[mods]]
modId="glass"
version="${version}"
displayName="${mod_name}"
authors="IMB11"
credits="Block models and textures by thepigcat"
description="${mod_description}"
iconFile="assets/glass/icon.png"

[[mixins]]
config="glass.mixins.json"

[[dependencies.glass]]
modId="neoforge"
type="required"
versionRange="${target_loader}"
ordering="NONE"
side="BOTH"

[[dependencies.glass]]
modId="minecraft"
type="required"
versionRange="${target_minecraft}"
ordering="NONE"
side="BOTH"

[features.glass]
javaVersion="[25,)"
