mod.id=mru
mod.name=MRU
mod.description=A library mod which provides various utilities for Cassian and IMB11's mods.
mod.license=MIT
mod.version=1.0.42
mod.group=cc.cassian.mru
publish.modrinth=SNVQ2c0g
publish.curseforge=669659
publish.mavenGroup=cc.cassian.mru
publish.dependencies.fabric=fabric-api
